module.exports = [
	{
		name: "Coastal Tiny House With Steel Frame",
	    type: "Tiny House",
	    builder: "dwalraven21@gmail.com",
	    description: "This tiny house can be custom built to order for you. Please inquire if you have questions and are interested in purchasing one for yourself!",
	    price: 79900,
	    image: "https://res.cloudinary.com/tinyhouselistings/image/upload/f_auto,q_auto:eco/e_trim/c_fill,h_592,w_896/IMG_20190501_181714919_HDR_sdc7ph_fz9f6t",
	    mobile: true,
		sqft: 180,
	    beds: 2,
	    baths: 1,
	    lofts: 2,
    },
	{
		name: "Brand New Tiny House",
		type: "Tiny House",
		builder: "dwalraven21@gmail.com",
		description: "This tiny house can be custom built to order for you. Please inquire if you have questions and are interested in purchasing one for yourself!",
		price: 70000,
		image: "https://res.cloudinary.com/tinyhouselistings/image/upload/f_auto,q_auto:eco/e_trim/c_fill,h_592,w_896/rkpTWSlM_azl396",
		mobile: true,
		sqft: 204,
		beds: 2,
		baths: 1,
		lofts: 1,
	},
	{
		name: "Art on Wheels!",
		type: "Tiny House",
		builder: "dwalraven21@gmail.com",
		description: "This tiny house can be custom built to order for you. Please inquire if you have questions and are interested in purchasing one for yourself!",
		price: 14000,
		image: "https://res.cloudinary.com/tinyhouselistings/image/upload/f_auto,q_auto:eco/e_trim/c_fill,h_592,w_896/2DBA2ECE-27E3-47ED-B7EF-7AF770660047_i1q7if",
		mobile: true,
		sqft: 54,
		beds: 1,
		baths: 0,
		lofts: 0,
	},
	{
		name: "Mt. Hood Lodge",
		type: "RV",
		builder: "dwalraven21@gmail.com",
		description: "This tiny house can be custom built to order for you. Please inquire if you have questions and are interested in purchasing one for yourself!",
		price: 106900,
		image: "https://res.cloudinary.com/tinyhouselistings/image/upload/f_auto,q_auto:eco/e_trim/c_fill,h_592,w_896/MtHoodLodge_km38xy",
		mobile: true,
		sqft: 432,
		beds: 2,
		baths: 1,
		lofts: 1,
	},
	{
		name: "NW Mountaineer",
		type: "Tiny House",
		builder: "dwalraven21@gmail.com",
		description: "This tiny house can be custom built to order for you. Please inquire if you have questions and are interested in purchasing one for yourself!",
		price: 45225,
		image: "https://res.cloudinary.com/tinyhouselistings/image/upload/f_auto,q_auto:eco/e_trim/c_fill,h_592,w_896/NWMountaineer_bv1yvc",
		mobile: true,
		sqft: 128,
		beds: 1,
		baths: 1,
		lofts: 1,
	},
	{
		name: "Tiny Traveler",
		type: "Camper",
		builder: "dwalraven21@gmail.com",
		description: "This tiny house can be custom built to order for you. Please inquire if you have questions and are interested in purchasing one for yourself!",
		price: 34500,
		image: "https://res.cloudinary.com/tinyhouselistings/image/upload/f_auto,q_auto:eco/e_trim/c_fill,h_592,w_896/Tiny_Traveler_n28v1y",
		mobile: true,
		sqft: 80,
		beds: 1,
		baths: 1,
		lofts: 1,
	},



	  ]
